/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* ===================================================================== */

//
// File: FT.idl
// CORBA 3.0 Chapter 23

#ifndef _CDMW_FT_FT_IDL_
#define _CDMW_FT_FT_IDL_

#include <FTPullMonitorable.idl>

#if defined(TAO)
// _FT_IDL_ is already defined in orbsvcs/FT_CORBA.idl

// The next include is TAO specific.
//#include <orbsvcs/FT_CORBA.idl>
// The OMG file has been split in to two portions.

// The next include is TAO specific.
#include "orbsvcs/FT_CORBA_ORB.idl"

//#include "orbsvcs/CosNaming.idl" // 98-10-19.idl
#include "CosNotification.idl" // from telecom/98-11-03.idl
#include "CosNotifyComm.idl"

#pragma prefix "omg.org"

/**
* This module describes interfaces and data types of the CORBA
* Fault Tolerance service.
*/

module FT
{
  /// Specification for the Common Types and Exceptions for
  /// ReplicationManager

  /// Forward declarations
  interface GenericFactory;
  interface FaultNotifier;

  /// Useful typedefs.
  typedef CORBA::RepositoryId _TypeId;
  typedef Object ObjectGroup;

//  typedef CosNaming::Name Name;
  typedef any Value;

  /**
   * @struct Property
   *
   * @brief A property name and a value association.
   */
  struct Property {
    Name nam;
    Value val;
  };

  /// Some mor euseful typedefs.
  typedef sequence<Property> Properties;
//  typedef Name Location;
  typedef sequence<Location> Locations;
  typedef Properties Criteria;

  /**
   * @struct FactoryInfo
   *
   * @brief <@todo>
   *
   */
  struct FactoryInfo {
    GenericFactory the_factory;
    Location the_location;
    Criteria the_criteria;
  };

  typedef sequence<FactoryInfo> FactoryInfos;

  typedef long ReplicationStyleValue;
  const ReplicationStyleValue STATELESS = 0;
  const ReplicationStyleValue COLD_PASSIVE = 1;
  const ReplicationStyleValue WARM_PASSIVE = 2;
  const ReplicationStyleValue ACTIVE = 3;
  const ReplicationStyleValue ACTIVE_WITH_VOTING = 4;
  typedef long MembershipStyleValue;
  const MembershipStyleValue MEMB_APP_CTRL = 0;
  const MembershipStyleValue MEMB_INF_CTRL = 1;
  typedef long ConsistencyStyleValue;
  const ConsistencyStyleValue CONS_APP_CTRL = 0;
  const ConsistencyStyleValue CONS_INF_CTRL = 1;
  typedef long FaultMonitoringStyleValue;
  const FaultMonitoringStyleValue PULL = 0;
  const FaultMonitoringStyleValue PUSH = 1;
  const FaultMonitoringStyleValue NOT_MONITORED = 2;
  typedef long FaultMonitoringGranularityValue;
  const FaultMonitoringGranularityValue MEMB = 0;
  const FaultMonitoringGranularityValue LOC = 1;
  const FaultMonitoringGranularityValue LOC_AND_TYPE = 2;
  typedef FactoryInfos FactoriesValue;
  typedef unsigned short InitialNumberReplicasValue;
  typedef unsigned short MinimumNumberReplicasValue;

  typedef TimeBase::TimeT CheckpointIntervalValue;
  exception InterfaceNotFound {};
  exception ObjectGroupNotFound {};
  exception MemberNotFound {};
  //exception ObjectNotFound {};
  exception MemberAlreadyPresent {};
  exception BadReplicationStyle {};
  exception ObjectNotCreated {};
  exception ObjectNotAdded {};
  exception PrimaryNotSet {};
  exception UnsupportedProperty {
    Name nam;
    Value val;
  };

  exception InvalidProperty {
    Name nam;
    Value val; };

  exception NoFactory {
    Location the_location;
    _TypeId type_id; };

  exception InvalidCriteria {
    Criteria invalid_criteria; };

  exception CannotMeetCriteria {
    Criteria unmet_criteria; };

  // Specification of PropertyManager Interface
  // which ReplicationManager Inherits

  interface PropertyManager {

    void set_default_properties(in Properties props)
      raises (InvalidProperty, UnsupportedProperty);
    Properties get_default_properties();

    void remove_default_properties(in Properties props)
      raises (InvalidProperty, UnsupportedProperty);

    void set_type_properties(in _TypeId type_id,
                             in Properties overrides)
      raises (InvalidProperty, UnsupportedProperty);

    Properties get_type_properties(in _TypeId type_id);

    void remove_type_properties(in _TypeId type_id,
                                in Properties props)
      raises (InvalidProperty, UnsupportedProperty);

    void set_properties_dynamically(in ObjectGroup object_group,
                                    in Properties overrides)
      raises(ObjectGroupNotFound, InvalidProperty, UnsupportedProperty);

    Properties get_properties(in ObjectGroup object_group)
      raises(ObjectGroupNotFound); };

  // Specification of ObjectGroupManager Interface
  // which ReplicationManager Inherits
  /**
	* This interface provides operations that allow an application to add, remove
	* and locate members of an object group and to obtain the current reference and
	* identifier for an object group.
	*
	*/

  interface ObjectGroupManager {
	 /**
	  * This operation allows the application to exercise explicit control over the
	  * creation of a member of an object group, and to determine where the member
	  * is created.
	  *
	  * @param object_group Reference for the object group to which the member is 
	  * to be added.
	  * @param the_location The physical location.
	  * @param type_id The repository identifier for the type of the object.
	  * @param the_criteria Parameters to be passed to the factory, which the factory
	  * evaluates before creating the object.
	  *
	  * @return The object group reference of the object group with the member added.
	  */
    ObjectGroup create_member(in ObjectGroup object_group,
                              in Location the_location,
                              in _TypeId type_id,
                              in Criteria the_criteria)
      raises(ObjectGroupNotFound,
             MemberAlreadyPresent,
             NoFactory,
             ObjectNotCreated,
             InvalidCriteria,
             CannotMeetCriteria);

	 /**
	  * This operation allows an application to add an existing object to an object 
	  * group at a particular location.
	  *
	  * @param object_group Reference for the object group to which the existing object 
	  * is to be added.
	  * @param the_location The physical location of the object to be added.
	  * @param member The reference of the object to be added.
	  *
	  * @return The object group reference of the object group with the object added.
	  */
    ObjectGroup add_member(in ObjectGroup object_group,
                           in Location the_location,
                           in Object member)
      raises(ObjectGroupNotFound,
             MemberAlreadyPresent,
             ObjectNotAdded);

	 /**
	  * This operation allows an application to remove a member from an object 
	  * group at a particular location.
	  *
	  * @param object_group Reference for the object group to which the member 
	  * is to be removed.
	  * @param the_location The physical location of the member to be removed.
	  *
	  * @return The object group reference of the member removed.
	  */
    ObjectGroup remove_member(in ObjectGroup object_group,
                              in Location the_location)
      raises(ObjectGroupNotFound,
             MemberNotFound);
	 
	 /**
	  * This operation allows the application to select the member of the object group 
	  * that is to be the primary.
	  *
	  * @param object_group Reference for the object group whose primary is to be 
	  * determined.
	  * @param the_location The physical location of the member that is to become 
	  * the primary.
	  *
	  * @return The object group reference with the primary member at the given 
	  * location.
	  */
    ObjectGroup set_primary_member(in ObjectGroup object_group,
                                   in Location the_location)
      raises(ObjectGroupNotFound,
             MemberNotFound,
             PrimaryNotSet,
             BadReplicationStyle);

    Locations locations_of_members(in ObjectGroup object_group)
      raises(ObjectGroupNotFound);

    ObjectGroupId get_object_group_id(in ObjectGroup object_group)
      raises(ObjectGroupNotFound);

    ObjectGroup get_object_group_ref(in ObjectGroup object_group)
      raises(ObjectGroupNotFound);

    Object get_member_ref(in ObjectGroup object_group,
                          in Location loc)
      raises(ObjectGroupNotFound, MemberNotFound); };


  // Specification of GenericFactory Interface
  // which ReplicationManager Inherits and Application Objects Implement
  /**
	* This interface allows the creation/deletion of replicated objects (object groups),
	* replicas (members of object groups), and unreplicated objects.
	*/
  interface GenericFactory {
    typedef any FactoryCreationId;

	 /**
	  * This operation creates an object or an object group, using the type_id 
	  * parameter to determine which type of object to create and the_criteria
	  * parameter to determine restrictions on how and where to create the object. 
	  *
	  * @param type_id The repository identifier of the object to be created by 
	  * the factory.
	  * 
	  * @param the_criteria Information passed to the factory, which the factory
	  * evaluates before creating the object. Examples of criteria are initialization
	  * values, constraints on the object, preferred location of the object, fault
	  * tolerance properties for an object group, etc.
	  * 
	  * @param factory_creation_id An identifier that allows the factory to delete
	  * the object subsequently.
	  *
	  * @return The reference to the object created by the GenericFactory. When the
	  * GenericFactory interface is implemented by the application’s local factory
	  * object, the create_object() operation returns an object reference as a result.
	  * When the GenericFactory interface is inherited by the Replication Manager, the
	  * create_object() operation returns an object group reference as a result.
	  *
	  * @exception NoFactory Raised if the factory cannot create an individual object
	  * of the type_id at the location.
	  * @exception ObjectNotCreated Raised if the factory cannot create the object.
	  * @exception InvalidCriteria Raised if the factory does not understand the criteria.
	  * @exception InvalidProperty Raised if a property passed in as criteria is invalid.
	  * @exception CannotMeetCriteria Raised if the factory understands the criteria but
	  * cannot satisfy it.
	  */
    Object create_object(in _TypeId type_id,
                         in Criteria the_criteria,
                         out FactoryCreationId factory_creation_id)
      raises (NoFactory,
              ObjectNotCreated,
              InvalidCriteria,
              InvalidProperty,
              CannotMeetCriteria);

	 /**
	  * This operation deletes the object/object group with the given identifier.
	  *
	  * @param factory_creation_id An identifier for the object that is to be deleted.
	  * 
	  * @exception ObjectNotFound Raised if the object cannot be found.
	  */
    void delete_object(in FactoryCreationId factory_creation_id)
      raises (ObjectNotFound); };

  // Specification of ReplicationManager Interface
  interface ReplicationManager : PropertyManager,
    ObjectGroupManager,
    GenericFactory {
    void register_fault_notifier(in FaultNotifier fault_notifier);
    FaultNotifier get_fault_notifier()
      raises (InterfaceNotFound); };

    // Specification of FaultNotifier Interface
    interface FaultNotifier {
	typedef unsigned long long ConsumerId;

	void push_structured_fault(
	    in CosNotification::StructuredEvent event);

	void push_sequence_fault(
	    in CosNotification::EventBatch events);

	ConsumerId connect_structured_fault_consumer(
	    in CosNotifyComm::StructuredPushConsumer push_consumer);

	ConsumerId connect_sequence_fault_consumer(
	    in CosNotifyComm::SequencePushConsumer push_consumer);
  
	void disconnect_consumer( 
	    in ConsumerId connection)
	    raises(CosEventComm::Disconnected);

        void replace_constraint(
            in ConsumerId connection,
            in CosNotification::EventTypeSeq event_types,
            in string constr_expr);
            
    };

  // Specifications for Logging and Recovery
  typedef sequence<octet> State;

  exception NoStateAvailable {};
  exception InvalidState {};

  exception NoUpdateAvailable {};
  exception InvalidUpdate {};

  // Specification of Checkpointable Interface
  // which Updateable and Application Objects Inherit
  interface Checkpointable { State get_state()
                               raises(NoStateAvailable);
  void set_state(in State s) raises(InvalidState); };

  // Specification of Updateable Interface
  // which Application Objects Inherit
  interface Updateable : Checkpointable { State get_update()
                                            raises(NoUpdateAvailable);
  void set_update(in State s) raises(InvalidUpdate);
  };

};

#else

#ifndef _FT_IDL_
#define _FT_IDL_

//#ifdef _PRE_3_0_COMPILER_
#if defined(ORBACUS)
//#include <OB/orb.idl>
//#include <OB/CosNaming.idl>
#include <OB/IOP.idl>
#include <FT_IOP.idl>
//#include <OB/CosNotification.idl>
#else
//#include <CosNaming.idl>
//#include <CosNotification.idl>
#include <IOP.idl>
//#include <orb.idl>
#endif
//#include <TimeBase.idl>
#include <CosEventComm.idl>
#include <GIOP.idl>

#pragma prefix "omg.org"

//#else
//import ::TimeBase;
//import ::CosNaming;
//import ::CosEventComm;
//import ::CosNotification;
//import ::IOP;
//import ::GIOP;
//import ::CORBA;
//#endif // _PRE_3_0_COMPILER_

/**
* This module describes interfaces and data types of the CORBA
* Fault Tolerance service.
*/

module FT {
//#ifndef _PRE_3_0_COMPILER_
//    typeprefix FT "omg.org";
//#endif // _PRE_3_0_COMPILER_


    // Specification for Interoperable Object Group References
    typedef string FTDomainId;
    typedef unsigned long long ObjectGroupId;
    typedef unsigned long ObjectGroupRefVersion;

    struct TagFTGroupTaggedComponent { // tag = TAG_FT_GROUP;
	     GIOP::Version		     version;
	     FTDomainId		     ft_domain_id;
	     ObjectGroupId		     object_group_id;
	     ObjectGroupRefVersion	     object_group_ref_version;
    };

    struct TagFTPrimaryTaggedComponent { // tag = TAG_FT_PRIMARY;
	     boolean			      primary;
    };

    // Specification for Most Recent Object Group Reference
    struct FTGroupVersionServiceContext { //context_id = FT_GROUP_VERSION;
	     ObjectGroupRefVersion		object_group_ref_version;
    };

    // Specification for Transparent Reinvocation
    const CORBA::PolicyType REQUEST_DURATION_POLICY = 47;
					
    struct FTRequestServiceContext { // context_id = FT_REQUEST;
	     string				client_id;
	     long				retention_id;
	     TimeBase::TimeT			expiration_time;
    };

    local interface RequestDurationPolicy : CORBA::Policy {
	     readonly attribute TimeBase::TimeT request_duration_value;
    };

    // Specification for Transport Heartbeats
    const CORBA::PolicyType HEARTBEAT_POLICY = 48;
    const CORBA::PolicyType HEARTBEAT_ENABLED_POLICY =  49;

    struct TagFTHeartbeatEnabledTaggedComponent { 
			// tag = TAG_FT_HEARTBEAT_ENABLED;
        	boolean				heartbeat_enabled;
    };

    struct HeartbeatPolicyValue {
	     boolean				heartbeat;
	     TimeBase::TimeT			heartbeat_interval;
	     TimeBase::TimeT			heartbeat_timeout;
    };

    local interface HeartbeatPolicy : CORBA::Policy {
	     readonly attribute HeartbeatPolicyValue heartbeat_policy_value;
    };

    local interface HeartbeatEnabledPolicy : CORBA::Policy {
        readonly attribute boolean heartbeat_enabled_policy_value;
    };

    // Specification of Common Types and Exceptions for ReplicationManager
    interface GenericFactory;
    interface FaultNotifier;

    typedef CORBA::RepositoryId TypeId;
    typedef Object ObjectGroup;

//    typedef CosNaming::Name Name;
    typedef any Value;

    struct Property {
	     Name	    nam;
	     Value	    val;
    };

    typedef sequence<Property> Properties;

//    typedef Name Location;
    typedef sequence<Location> Locations;
    typedef Properties Criteria;

    struct FactoryInfo {
	     GenericFactory	the_factory;
	     Location	the_location;
	     Criteria	the_criteria;
    };

    typedef sequence<FactoryInfo>  FactoryInfos;

    typedef unsigned short ReplicationStyleValue;
    const ReplicationStyleValue		STATELESS	= 0;
    const ReplicationStyleValue		COLD_PASSIVE	= 1;
    const ReplicationStyleValue		WARM_PASSIVE	= 2;
    const ReplicationStyleValue		ACTIVE		= 3;
    const ReplicationStyleValue		ACTIVE_WITH_VOTING = 4;

    typedef unsigned short MembershipStyleValue;
    const MembershipStyleValue		MEMB_APP_CTRL	= 0;
    const MembershipStyleValue		MEMB_INF_CTRL	= 1;

    typedef unsigned short ConsistencyStyleValue; 
    const ConsistencyStyleValue		CONS_APP_CTRL	= 0;
    const ConsistencyStyleValue		CONS_INF_CTRL	= 1;

    typedef unsigned short FaultMonitoringStyleValue;
    const FaultMonitoringStyleValue	PULL		= 0;
    const FaultMonitoringStyleValue	PUSH		= 1;
    const FaultMonitoringStyleValue	NOT_MONITORED	= 2;

    typedef unsigned short FaultMonitoringGranularityValue;
    const FaultMonitoringGranularityValue MEMB		= 0;
    const FaultMonitoringGranularityValue LOC		= 1;
    const FaultMonitoringGranularityValue LOC_AND_TYPE	= 2;

    typedef FactoryInfos FactoriesValue;

    typedef unsigned short InitialNumberReplicasValue;
    typedef unsigned short MinimumNumberReplicasValue;

    typedef TimeBase::TimeT CheckpointIntervalValue;
					
    exception InterfaceNotFound {};
    exception ObjectGroupNotFound {};
    exception MemberNotFound {};
    //exception ObjectNotFound {};
    exception MemberAlreadyPresent {};
    exception BadReplicationStyle {};
    exception ObjectNotCreated {};
    exception ObjectNotAdded {};
    exception PrimaryNotSet {};
    exception UnsupportedProperty {
	     Name  nam;
	     Value val;
    };
    exception InvalidProperty {
	     Name  nam;
	     Value val;
    };
    exception NoFactory {
	     Location	the_location;
	     TypeId		type_id;
    };
    exception InvalidCriteria {
	     Criteria invalid_criteria;
    };
    exception CannotMeetCriteria {
	     Criteria unmet_criteria;
    };

    // Specification of PropertyManager Interface 
    // which ReplicationManager Inherits
    interface PropertyManager {
	     void set_default_properties(in Properties props)
	         raises (InvalidProperty,
		              UnsupportedProperty);

	     Properties get_default_properties();

	     void remove_default_properties(in Properties props)
	         raises (InvalidProperty,
		              UnsupportedProperty);

	     void set_type_properties(
	                 in TypeId type_id,
	                 in Properties overrides)
	         raises (InvalidProperty,
		              UnsupportedProperty);

	     Properties get_type_properties(in TypeId type_id);

	     void remove_type_properties(
	                 in TypeId type_id,
	                 in Properties props)
	         raises (InvalidProperty,
		              UnsupportedProperty);

	     void set_properties_dynamically(
	                 in ObjectGroup object_group,
	                 in Properties overrides)
	         raises(ObjectGroupNotFound,
		             InvalidProperty,
		             UnsupportedProperty);

	     Properties get_properties(in ObjectGroup object_group)
	         raises(ObjectGroupNotFound);
    };


    // Specification of ObjectGroupManager Interface
    // which ReplicationManager Inherits
    /**
     * This interface provides operations that allow an application to add, remove
     * and locate members of an object group and to obtain the current reference and
     * identifier for an object group.
     *
     */

    interface ObjectGroupManager {

      /**
       * This operation allows the application to exercise explicit control over the
       * creation of a member of an object group, and to determine where the member
       * is created.
       *
       * @param object_group Reference for the object group to which the member is 
       * to be added.
       * @param the_location The physical location.
       * @param type_id The repository identifier for the type of the object.
       * @param the_criteria Parameters to be passed to the factory, which the factory
       * evaluates before creating the object.
	    *
       * @return The object group reference of the object group with the member added.
       */

	     ObjectGroup create_member(
	             in ObjectGroup object_group,
	             in Location the_location,
	             in TypeId type_id, 
	             in Criteria the_criteria)
	         raises(ObjectGroupNotFound,
		             MemberAlreadyPresent,
		             NoFactory,
		             ObjectNotCreated,
		             InvalidCriteria,
		             CannotMeetCriteria);
						
      /**
	    * This operation allows an application to add an existing object to an object 
	    * group at a particular location.
	    *
	    * @param object_group Reference for the object group to which the existing object 
	    * is to be added.
	    * @param the_location The physical location of the object to be added.
	    * @param member The reference of the object to be added.
	    *
	    * @return The object group reference of the object group with the object added.
	    */
	     ObjectGroup add_member(
	             in ObjectGroup object_group,
	             in Location the_location,
	             in Object member)
	         raises(ObjectGroupNotFound,
		             MemberAlreadyPresent,
		             ObjectNotAdded);

	   /**
	    * This operation allows an application to remove a member from an object 
	    * group at a particular location.
	    *
	    * @param object_group Reference for the object group to which the member 
	    * is to be removed.
	    * @param the_location The physical location of the member to be removed.
	    *
	    * @return The object group reference of the member removed.
	    */
	     ObjectGroup remove_member(
	             in ObjectGroup object_group,
	             in Location the_location)
	         raises(ObjectGroupNotFound,
		             MemberNotFound);
		
	   /**
	    * This operation allows the application to select the member of the object group 
	    * that is to be the primary.
	    *
	    * @param object_group Reference for the object group whose primary is to be 
	    * determined.
	    * @param the_location The physical location of the member that is to become 
	    * the primary.
	    *
	    * @return The object group reference with the primary member at the given 
	    * location.
	    */				
	     ObjectGroup set_primary_member(
                in ObjectGroup object_group,
	             in Location the_location)
	         raises(ObjectGroupNotFound,
		             MemberNotFound,
		             PrimaryNotSet,
		             BadReplicationStyle);
						
	     Locations locations_of_members(
	             in ObjectGroup object_group)
	         raises(ObjectGroupNotFound);
						
	     ObjectGroupId get_object_group_id(
	             in ObjectGroup object_group)
	         raises(ObjectGroupNotFound);

	     ObjectGroup get_object_group_ref(
	             in ObjectGroup object_group)
	         raises(ObjectGroupNotFound);

	     Object get_member_ref(
	             in ObjectGroup object_group,
	             in Location loc)
	         raises(ObjectGroupNotFound,
	                MemberNotFound);
    };

    // Specification of GenericFactory Interface
    // which ReplicationManager Inherits and Application Objects Implement
    /**
     * This interface allows the creation/deletion of replicated objects (object groups),
	  * replicas (members of object groups), and unreplicated objects.
	  */
    interface GenericFactory {
        typedef any FactoryCreationId; 

	     /**
	      * This operation creates an object or an object group, using the type_id 
	      * parameter to determine which type of object to create and the_criteria
	      * parameter to determine restrictions on how and where to create the object. 
	      *
	      * @param type_id The repository identifier of the object to be created by 
	      * the factory.
	      * 
	      * @param the_criteria Information passed to the factory, which the factory
	      * evaluates before creating the object. Examples of criteria are initialization
	      * values, constraints on the object, preferred location of the object, fault
	      * tolerance properties for an object group, etc.
	      * 
	      * @param factory_creation_id An identifier that allows the factory to delete
	      * the object subsequently.
	      *
	      * @return The reference to the object created by the GenericFactory. When the
	      * GenericFactory interface is implemented by the application’s local factory
	      * object, the create_object() operation returns an object reference as a result.
	      * When the GenericFactory interface is inherited by the Replication Manager, the
	      * create_object() operation returns an object group reference as a result.
	      *
	      * @exception NoFactory Raised if the factory cannot create an individual object
	      * of the type_id at the location.
	      * @exception ObjectNotCreated Raised if the factory cannot create the object.
	      * @exception InvalidCriteria Raised if the factory does not understand the criteria.
	      * @exception InvalidProperty Raised if a property passed in as criteria is invalid.
	      * @exception CannotMeetCriteria Raised if the factory understands the criteria but
	      * cannot satisfy it.
	      */
	     Object create_object(in TypeId type_id, 
	                          in Criteria the_criteria,
	                          out FactoryCreationId factory_creation_id)
	         raises (NoFactory,
		              ObjectNotCreated,
		              InvalidCriteria,
		              InvalidProperty,
		              CannotMeetCriteria);

	     /**
	      * This operation deletes the object/object group with the given identifier.
	      *
	      * @param factory_creation_id An identifier for the object that is to be deleted.
	      * 
	      * @exception ObjectNotFound Raised if the object cannot be found.
	      */
	     void delete_object(
	             in FactoryCreationId factory_creation_id)
	         raises (ObjectNotFound);
	};

	// Specification of ReplicationManager Interface
	interface ReplicationManager : PropertyManager, 
				                      ObjectGroupManager,
				                      GenericFactory {
	     void register_fault_notifier(
	             in FaultNotifier fault_notifier);

	     FaultNotifier get_fault_notifier()
	         raises (InterfaceNotFound);
    };

    // Specification of FaultNotifier Interface
    interface FaultNotifier {
	/*typedef unsigned long long ConsumerId;

	void push_structured_fault(
	    in CosNotification::StructuredEvent event);

	void push_sequence_fault(
	    in CosNotification::EventBatch events);

	ConsumerId connect_structured_fault_consumer(
	    in CosNotifyComm::StructuredPushConsumer push_consumer);

	ConsumerId connect_sequence_fault_consumer(
	    in CosNotifyComm::SequencePushConsumer push_consumer);
  
	void disconnect_consumer( 
	    in ConsumerId connection)
	    raises(CosEventComm::Disconnected);

        void replace_constraint(
            in ConsumerId connection,
            in CosNotification::EventTypeSeq event_types,
            in string constr_expr);
            */
    };

    // Specifications for Logging and Recovery
    typedef sequence<octet> State;

    exception NoStateAvailable {};
    exception InvalidState {};
    exception NoUpdateAvailable {};
    exception InvalidUpdate {};

    // Specification of Checkpointable Interface
    // which Updateable and Application Objects Inherit
    interface Checkpointable {
	State  get_state()
	    raises(NoStateAvailable);

	void set_state(in State s)
	    raises(InvalidState);
    };

    // Specification of Updateable Interface
    // which Application Objects Inherit
    interface Updateable : Checkpointable {
	State  get_update() 
	    raises(NoUpdateAvailable);

	void set_update(in State s)
	     raises(InvalidUpdate);
    };
};
#endif          // for #ifndef _FT_IDL_

#endif  // if defined (TAO)

#endif // _CDMW_FT_FT_IDL_
