/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* ===================================================================== */


#ifndef CDMW_PLATFORM_MNGT_PROCESS_DELEGATE_WRAPPER_IDL_
#define CDMW_PLATFORM_MNGT_PROCESS_DELEGATE_WRAPPER_IDL_


#include <CdmwPlatformMngtBase.idl>
#include <CdmwPlatformMngtCommonBase.idl>
#include <CdmwPlatformMngtCommon.idl>
#include <CdmwPlatformMngtCommandBase.idl>
#include <CdmwPlatformMngtMonitoring.idl>

#include <CdmwPlatformMngtProcessDelegate.idl>

#pragma prefix "thalesgroup.com"

module CdmwPlatformMngt
{
    /**
     * The managed process delegate interface.
     */
    interface ProcessDelegateWrapper : ProcessDelegate
    {
        /**
        * Requests the process to initialise or to perform its first step
        * of initialisation.
        *
        * @param startup_kind the startup kind of the whole system.
        *
	    * @param init_timeout the maximum time budget for the process to get initialised.
	    *
	    * @return the result of command
	    *
        */
        ProcessCommandResult initialise_process (
                                  in CdmwPlatformMngtBase::StartupKind startup_kind, 
                                  in Timeout init_timeout);
        
        /**
        * Requests the process to perform its next step of initialisation.
        *
        * @param next_step_timeout the maximum time budget for the process to reach the next step.
        *
        * @return the result of command
        *
        */
        ProcessCommandResult next_step_process (
                                in unsigned long step_number, 
                                in Timeout next_step_timeout);

        /**
        * Requests the process to run.
        *
        * @param run_timeout the maximum time budget for the process to reach the running mode.
        *
        * @return the result of command
        *
        */
        ProcessCommandResult run_process (in Timeout run_timeout);

        /**
        * Requests the process to stop properly.
        *
        * @param stop_timeout the maximum time budget for the process to stop properly.
        *
        * @return the result of command
        *
        */
        ProcessCommandResult stop_process (in Timeout stop_timeout);
        
        /**
        * Requests the information about command result.
        *
        * @return the result info about the command
        *
        */
        string get_command_result_info ();
        
        
    }; // End interface ProcessDelegateWrapper


}; // End Module CdmwPlatformMngt

#endif // CDMW_PLATFORM_MNGT_PROCESS_DELEGATE_WRAPPER_IDL_

