/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* ===================================================================== */

#ifndef _CdmwFTSimpleMonitoring_IDL
#define _CdmwFTSimpleMonitoring_IDL

#include "CdmwFTMonitoring.idl"

#pragma prefix "thalesgroup.com"

/**
 * This module describes interfaces and data types of the Monitoring Library.
 */
module CdmwFT {
module MonitoringLibrary
{

    /**
     * This module describes interfaces and data types of the Monitoring
     * Library for Simple monitoring of remote locations.
     */
    module SimpleMonitoring
    {
        /**
    	 * Interface to be supported by the simple monitoring object with
         * interrogating role. It is responsible for monitoring other locations
         * with acknowledging role to detect their failure.
         */ 
        local interface InterrogatingSimpleMonitoring : Monitoring
        {
            /**
             * Adds <i>the_location</i> to the list of locations to be monitored.
             *
             * @param the_location The location to be monitored.
             *
             * @exception LocationAlreadyExists Raised if the location is already
             * known to the monitoring library.
             */             
            void add_location(in Location the_location)
                raises (AlreadyExists);

            /**
             * Removes <i>the_location</i> from the list of monitored locations.
             *
             * @param the_location The location to be remove.
             *
             * @exception NotFound Raised if the location was not monitored locally.
             */             
            void remove_location(in Location the_location)
                raises (NotFound);

            /**
             * Sets the set of locations to be monitored. This is only possible
             * if there are no locations yet. Otherwise a call to reset_locations
             * have to be made before calling this operation.
             *
             * @param the_locations A sequence of Locations.
             *
             * @exception NotEmpty Raised if there is already a list of locations.
             */
            void set_locations(in Locations the_locations)
                raises (NotEmpty);

            /**
             * Reset all locations. No location to monitor.
             */
            void reset_locations();
            
            /**
             * Attach an observer to be called when some other locations fails.
             * An exception is raised if the observer has already been attached.
             *
             * @param the_observer The MonitoringObserver to attach.
             *
             * @exception AlreadyExists Raised when <i>the_observer</i> has
             * alreay been attached.
             */
            void attach_observer(in MonitoringObserver the_observer)
                raises (AlreadyExists);

             /**
             *
             * Detaches previously attached observer. There will be no further call
             * to <i>the_observer</i>. An exception will be raised if <i>the_observer</i>
             * was not attached previously.
             *
             * @param the_observer The MonitoringObserver to detach.
             *
             * @exception NotFound Raised whenever <i>the_observer</i> was not
             * attached previously.
             **/
            void detach_observer(in MonitoringObserver the_observer)
                raises (NotFound);
        };
        /**
    	 * Interface to be supported by the simple monitoring object with
         * acknowledging role. It is responsible for acknowledging interrogations
         * from simple monitoring object with interrogationg role.
         */ 
        local interface AcknowledgingSimpleMonitoring : Monitoring {};
    };
};
};
#endif 
