// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package com.thalesgroup.HelloModule;

//
// IDL:thalesgroup.com/HelloModule/HelloInterface:1.0
//
final public class HelloInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
    public HelloInterface value;

    public
    HelloInterfaceHolder()
    {
    }

    public
    HelloInterfaceHolder(HelloInterface initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = HelloInterfaceHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        HelloInterfaceHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return HelloInterfaceHelper.type();
    }
}
