/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES 
 * and SELEX-SI. 
 * 
 * It is derivative work based on PERCO Copyright (C) THALES 2000-2003. 
 * All rights reserved.
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it under 
 * the terms of the GNU Library General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your 
 * option) any later version. 
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public 
 * License for more details. 
 * 
 * You should have received a copy of the GNU Library General 
 * Public License along with CARDAMOM; see the file COPYING. If not, write to 
 * the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* ===================================================================== */

#ifndef TYPECODE_IDL
#define TYPECODE_IDL

//
// From the CORBA 2.4 specification:
//
// IDL files that use CORBA::TypeCode may obtain its definition by
// including either the file orb.idl or the file TypeCode.idl.
//
#pragma inhibit_code_generation
//
// NOTE: This is a proprietary pragma which enables CORBA::TypeCode.
//
// DO NOT TRANSLATE THIS FILE!
//
#pragma prefix "omg.org"
//#pragma TypeCode
module CORBA {
	// See CORBA Specifications - 3.14 CORBA Module
	pseudo interface TypeCode {
	};
};


#endif
