ctools::time::HighResClock Class Reference
This class provide a way of getting access to high resolution clock available on Pentium microprocessors.
#include <HighResClock.h>
Static Public Member Functions
HighResTime getTime ()
void getTime (HighResTime &time)
unsigned long long getClockTickCount ()
double getClockFrequency ()
double getClockPeriod ()
Detailed Description
This class provide a way of getting access to high resolution clock available on Pentium microprocessors.
This clock has the same resolution of the hardware clock of the machine. The time measured by this clock is that elapsed since the boot up of the machine.
Author: Angelo Corsaro
Version: 1.0
Definition at line 39 of file HighResClock.h.
Member Function Documentation
double ctools::time::HighResClock::getClockFrequency () [static]
Definition at line 42 of file HighResClock.cc.
References CLOCK_FREQUENCY.
double ctools::time::HighResClock::getClockPeriod () [static]
Definition at line 51 of file HighResClock.cc.
References CLOCK_PERIOD_NS.
unsigned long long ctools::time::HighResClock::getClockTickCount () [static]
Definition at line 59 of file HighResClock.cc.
Referenced by ctools::time::HighResTimer::start(), and ctools::time::HighResTimer::stop().
void ctools::time::HighResClock::getTime (HighResTime & time) [static]
Definition at line 18 of file HighResClock.cc.
References CLOCK_PERIOD_NS, POW_6_TEN, and ctools::time::HighResTime::set().
ctools::time::HighResTime ctools::time::HighResClock::getTime () [static]
Definition at line 10 of file HighResClock.cc.
The documentation for this class was generated from the following files:
HighResClock.h
HighResClock.cc