ctools::time::HighResTimer Class Reference
This class provide a way of performing high resolution of the time spent performing something.
#include <HighResTimer.h>
Public Member Functions
HighResTimer ()
void start ()
Starts measuring the elapsed time.
void stop ()
Stops the time measurement.
void reset ()
Resets the timer.
ctools::time::HighResTime getElapsedTime ()
void getElapsedTime (ctools::time::HighResTime &time)
Detailed Description
This class provide a way of performing high resolution of the time spent performing something.
Author: Angelo Corsaro
Version: 1.0
Definition at line 38 of file HighResTimer.h.
Constructor & Destructor Documentation
ctools::time::HighResTimer::HighResTimer () [inline]
Definition at line 41 of file HighResTimer.h.
Member Function Documentation
void ctools::time::HighResTimer::getElapsedTime (ctools::time::HighResTime & time) [inline]
Definition at line 71 of file HighResTimer.h.
References ctools::time::HighResTime::set().
ctools::time::HighResTime ctools::time::HighResTimer::getElapsedTime () [inline]
Definition at line 67 of file HighResTimer.h.
void ctools::time::HighResTimer::reset () [inline]
Resets the timer.
Definition at line 63 of file HighResTimer.h.
void ctools::time::HighResTimer::start () [inline]
Starts measuring the elapsed time.
Definition at line 47 of file HighResTimer.h.
References ctools::time::HighResClock::getClockTickCount().
void ctools::time::HighResTimer::stop () [inline]
Stops the time measurement.
Definition at line 55 of file HighResTimer.h.
References ctools::time::HighResClock::getClockTickCount().
The documentation for this class was generated from the following file:
HighResTimer.h