ctools::time::HighResTime Class Reference
#include <HighResTime.h>
Public Types
typedef unsigned long long time_t
Public Member Functions
HighResTime (time_t clockTicks=0)
Creates a HighResTime(p.) and initializes it with the time represented by the clockTicks times the machine clock period.
HighResTime (time_t msec, time_t nsec)
Creates a HighResTime(p.) object and initializes it with a given time expressed in milliseconds and nanoseconds.
HighResTime (const HighResTime &time)
Creates a HighResTime(p.) object and initializes it with a given time object;.
~HighResTime ()
time_t millisec () const
void millisec (time_t msec)
time_t nanosec () const
void nanosec (time_t nsec)
void set (time_t msec, time_t nsec)
void set (time_t clockTicks)
void reset ()
long double toMillisec () const
long double toMicrosec () const
long double toNanosec () const
HighResTime operator+ (const HighResTime &rhs)
HighResTime operator- (const HighResTime &rhs)
const HighResTime & operator= (const HighResTime &rhs)
Member Typedef Documentation
typedef unsigned long long ctools::time::HighResTime::time_t
Definition at line 33 of file HighResTime.h.
Referenced by HighResTime(), millisec(), nanosec(), and set().
Constructor & Destructor Documentation
ctools::time::HighResTime::HighResTime (time_t clockTicks = 0) [explicit]
Creates a HighResTime(p.) and initializes it with the time represented by the clockTicks times the machine clock period.
Parameters:
clockTicks the number of hardware clock tics that have to be used in order to initialize the timer.
Definition at line 6 of file HighResTime.cc.
References set(), and time_t.
Referenced by operator+(), and operator-().
ctools::time::HighResTime::HighResTime (time_t msec, time_t nsec)
Creates a HighResTime(p.) object and initializes it with a given time expressed in milliseconds and nanoseconds.
Parameters:
msec the millisecond component of the time.
nsec the nanosecond compomnent of the time.
Definition at line 11 of file HighResTime.cc.
References set(), and time_t.
ctools::time::HighResTime::HighResTime (const HighResTime & time)
Creates a HighResTime(p.) object and initializes it with a given time object;.
Definition at line 16 of file HighResTime.cc.
ctools::time::HighResTime::~HighResTime ()
Definition at line 21 of file HighResTime.cc.
Member Function Documentation
void ctools::time::HighResTime::millisec (time_t msec)
Definition at line 30 of file HighResTime.cc.
References time_t.
ctools::time::HighResTime::time_t ctools::time::HighResTime::millisec () const
Definition at line 24 of file HighResTime.cc.
Referenced by operator+(), operator-(), operator<<(), and operator=().
void ctools::time::HighResTime::nanosec (time_t nsec)
Definition at line 42 of file HighResTime.cc.
References time_t.
ctools::time::HighResTime::time_t ctools::time::HighResTime::nanosec () const
Definition at line 36 of file HighResTime.cc.
Referenced by operator+(), operator-(), operator<<(), and operator=().
ctools::time::HighResTime ctools::time::HighResTime::operator+ (const HighResTime & rhs)
Definition at line 97 of file HighResTime.cc.
References HighResTime(), millisec(), and nanosec().
ctools::time::HighResTime ctools::time::HighResTime::operator- (const HighResTime & rhs)
Definition at line 104 of file HighResTime.cc.
References HighResTime(), millisec(), and nanosec().
const ctools::time::HighResTime & ctools::time::HighResTime::operator= (const HighResTime & rhs)
Definition at line 111 of file HighResTime.cc.
References millisec(), nanosec(), and set().
void ctools::time::HighResTime::reset ()
Definition at line 72 of file HighResTime.cc.
References set().
void ctools::time::HighResTime::set (time_t clockTicks)
Definition at line 48 of file HighResTime.cc.
References CLOCK_PERIOD_NS, POW_6_TEN, set(), and time_t.
void ctools::time::HighResTime::set (time_t msec, time_t nsec)
Definition at line 59 of file HighResTime.cc.
References POW_6_TEN, and time_t.
Referenced by ctools::time::HighResTimer::getElapsedTime(), ctools::time::HighResClock::getTime(), HighResTime(), operator=(), reset(), and set().
long double ctools::time::HighResTime::toMicrosec () const
Definition at line 84 of file HighResTime.cc.
References POW_3_TEN.
long double ctools::time::HighResTime::toMillisec () const
Definition at line 78 of file HighResTime.cc.
References POW_6_TEN.
long double ctools::time::HighResTime::toNanosec () const
Definition at line 90 of file HighResTime.cc.
References POW_6_TEN.
The documentation for this class was generated from the following files:
HighResTime.h
HighResTime.cc