/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* ===================================================================== */


#ifndef  TEST_HELLO_IDL_
#define  TEST_HELLO_IDL_

#pragma prefix "thalesgroup.com"


module CdmwRequestLogging {    

    
   typedef sequence<string> LogSeq;
  /** 
   * Hello interface
   */
  interface HelloInterface {

    void hello();
    
    /**
     * do_something return a simple value to be recorded
     */
    long do_something(in long val);

    /**
     * get_log_size return number of entries in reply datastore
     */
    long get_log_size();

  };

  interface HelloLogger {
     /**
     * get_log_traces return sequence of log registered by each datastore
     * observer and each server interceptor.
     */
    LogSeq get_log_traces();

    /**
     * set_log_trace stores trace in a sequence of log. This operation will
     * be invoked by each datastore observer and each server interceptor.
     */
    void set_log_trace(in string trace);
  };
}; 

#endif // TEST_HELLO_IDL_

