// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2001
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.1.0

package com.thalesgroup.HelloModule;

//
// IDL:thalesgroup.com/HelloModule/HelloInterface:1.0
//
/***/

public interface HelloInterface extends HelloInterfaceOperations,
                                        org.omg.CORBA.Object,
                                        org.omg.CORBA.portable.IDLEntity
{
}
