# File generated by jtk_idl_depend.sh. DO NOT EDIT
# Created on: gio feb  3 18:44:34 CET 2005.
# ORB: tao13

CORBA_DISPATCHER_IDL	= ../idl/Dispatcher.idl
CORBA_DISPATCHER_CL_SRC	= DispatcherC.cpp
CORBA_DISPATCHER_SRV_SRC	= DispatcherC.cpp DispatcherS.cpp
CORBA_DISPATCHER_CL_OBJS	= DispatcherC.o
CORBA_DISPATCHER_SRV_OBJS	= DispatcherC.o DispatcherS.o
CORBA_DISPATCHER_CL_HDRS	= DispatcherC.h Dispatcher.stub.hpp
CORBA_DISPATCHER_SRV_HDRS	= DispatcherC.h DispatcherS.h Dispatcher.skel.hpp

CORBA_ALL_IDL	=  \
	../idl/Dispatcher.idl
CORBA_CL_ALL_SRC	=  \
	DispatcherC.cpp
CORBA_SRV_ALL_SRC	=  \
	DispatcherC.cpp DispatcherS.cpp
CORBA_CL_ALL_OBJS	=  \
	DispatcherC.o
CORBA_SRV_ALL_OBJS	=  \
	DispatcherC.o DispatcherS.o
CORBA_CL_ALL_HDRS	=  \
	DispatcherC.h Dispatcher.stub.hpp
CORBA_SRV_ALL_HDRS	=  \
	DispatcherC.h DispatcherS.h Dispatcher.skel.hpp
