/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES 
 * and SELEX-SI. 
 * 
 * It is derivative work based on PERCO Copyright (C) THALES 2000-2003. 
 * All rights reserved.
 * 
 * This file and the information it contains are confidential and proprietary. 
 * They shall not be reproduced nor disclosed to any person except to those 
 * having a need to know them without prior written consent of the owner.
*/
/* ===================================================================== */


#ifndef  TEST_HELLO_IDL_
#define  TEST_HELLO_IDL_
#include <CdmwFTStateTransfer.idl>
#pragma prefix "thalesgroup.com"


module CdmwReplicationManager {    
    
    /** 
     * Hello interface
     */
    interface HelloInterface {
        
        /**
         * insert
         */
        void insert(in long dsid, in long oid, in string data);
        
        /**
         * get_data
         */
        string get_data(in long dsid, in long oid);
        
        /**
         * ping
         */
        void ping();
        
    };

    struct timestruct
    {
        unsigned long second;
        unsigned long microsecond;
    };
    
    

    interface time_collector
    {
        /**
         * set_init_primary_data_stores_time
         */
        
        void set_init_primary_data_stores_time(in timestruct time);
        
        /**
         * set_get_record_iterator_time()
         */
        void set_get_record_iterator_time(in timestruct time);

        /**
         * get_init_primary_data_stores_time
         */
        
        timestruct get_init_primary_data_stores_time();
        
        /**
         * get_get_record_iterator_time()
         */
        timestruct get_get_record_iterator_time();
    };
}; 

#endif // TEST_HELLO_IDL_

