/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES 
 * and SELEX-SI. 
 * 
 * It is derivative work based on PERCO Copyright (C) THALES 2000-2003. 
 * All rights reserved.
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it under 
 * the terms of the GNU Library General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your 
 * option) any later version. 
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public 
 * License for more details. 
 * 
 * You should have received a copy of the GNU Library General 
 * Public License along with CARDAMOM; see the file COPYING. If not, write to 
 * the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* ===================================================================== */


#pragma prefix "thalesgroup.com"

module Test {
   struct Struct1 {
      long long1;
      string string1;
   };

   typedef sequence <Struct1, 5> Struct1Seq;

   valuetype Value1 {
      public Struct1Seq member1;
   };

   typedef sequence <Value1> Value1Seq;

   typedef sequence <Value1Seq> Value1SeqSeq;
   
   interface Interface1 {
   };
   
   enum TestEnum
   {
      A, B, C
   };

   typedef sequence<TestEnum> TestEnumSeq;

   interface Component1 {
      attribute short         attrib1;
      attribute unsigned long attrib2;
      attribute Struct1       attrib3;
      attribute Struct1Seq    attrib4;
      attribute Value1        attrib5;
      attribute Value1Seq     attrib6;
      attribute Value1SeqSeq  attrib7;
      attribute TestEnum      attrib8;
      attribute TestEnumSeq   attrib9;
   };

};

