/* ===================================================================== */
/*
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
/* ===================================================================== */

/* =========================================================================== * 
 * This code has been generated by CDMW Code Generator 1.0
 * on Fri Mar 11 13:23:25 CET 2005
 * DO NOT EDIT !!!
 * =========================================================================== */
#include "namingandrepository/CdmwNamingAndRepositoryDatastoreEntities.stub.hpp"

#ifndef __DECLARE_CDMWNAMINGANDREPOSITORY_STORAGEDATA_TYPE_TRAITS__
#define __DECLARE_CDMWNAMINGANDREPOSITORY_STORAGEDATA_TYPE_TRAITS__
DEFINE_VARIABLE_LENGTH_DATA_TRAITS(CdmwNamingAndRepository::StorageData);
#endif // __DECLARE_CDMWNAMINGANDREPOSITORY_STORAGEDATA_TYPE_TRAITS__
